### PR TITLE
Add ffi test cases

### PR DESCRIPTION
**Pull request by qur786**

### CODE REVIEW

**Comment by maneetgoyal** [comment]
@qur786 Keep a check the GH actions status. The build was running an infinite loop consuming too many resources (> 4 hrs):

Screenshot 2021-09-04 at 12 52 53 PM

**Comment by maneetgoyal** [comment]
@qur786 When you want to pass a reference-to-an-object as an input argument, use `object.ref()` instead of `refNAPI.refType(object)`.

Have fixed some tests. Try to fix others via the same approach of turning `refNAPI.refType(object)` ==> `object.ref()` where applicable.

**Comment by maneetgoyal** [comment]
@qur786 Let me know once it is ready for review, also try to make the CI green

**Comment by qur786** [comment]
> @qur786 Let me know once it is ready for review, also try to make the CI green

Sir it is actually ready , the CI is failing because we have imported `InchiInpData` but commented out the test which uses `InchiInpData`.so it is failing due to not using the above function.

**Comment by maneetgoyal** [comment]
@qur786 In that case, remove that import and trigger the CI again.

**Comment by qur786** [comment]
> @qur786 In that case, remove that import and trigger the CI again.

@maneetgoyal Sir I commented out the import and now it is passing

**Review by maneetgoyal — APPROVED** [review]

**Pull request merged**
